export const images = {
    onboardOne: require('./onboard-1.png'),
    onboardTwo: require('./onboard-2.png'),
    onboardThree: require('./onboard-3.png'),
    onboardFour: require('./onboard-4.png'),
    topArea: require('./TopArea.png'),
    globe: require('./globe.png'),
    foodCat1: require('./food-cat1.png'),
    foodCat2: require('./food-cat2.png'),
    foodCat3: require('./food-cat3.png'), 
    foodCat4: require('./food-cat4.png'),
    rest1: require('./rest1.png'),
    rest2: require('./rest2.png'),
    rest3: require('./rest3.png'),
    item1: require('./item-1.png'),
    item2: require('./item-2.png'),
    item3: require('./item-3.png'),
    item4: require('./item-4.png'),
    skewedBg: require('./skewed-bg.png'),
    restBg: require('./restBg.png'),
    foodPrev: require('./food.png'),
}