export const icons = {
    eyeOpen: require('./eye-open.png'),
    eyeClosed: require('./eye-closed.png'),
    x: require('./x.png'),
    facebook: require('./facebook.png'),
    apple: require('./apple.png'),
    mapPin: require('./map-pin.png'),
    person: require('./ion_person.png'),
    cart: require('./Cart.png'),
    menu: require('./Menu.png'),
    dropdown: require('./Polygon.png'),
    search: require('./Search.png'),
    right_arr: require('./right_arr.png'),
    star: require('./Star.png'),
    delivery: require('./Delivery.png'),
    clock: require('./Clock.png'),
    close: require('./close.png'),
    back: require('./Back.png'),
    resultSearch: require('./Search-icon.png'),
    filter: require('./Filter.png'),
    cross: require('./Cross.png'),
    starFilled: require('./star_filled.png'),
    starOutlined: require('./star_outline.png'),
}